# Generated by Django 5.1.13 on 2025-10-03 16:47

import django.db.models.deletion
import streamer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('clip_file', models.FileField(blank=True, null=True, upload_to=streamer.models.secure_audio_clip_path, validators=[streamer.models.validate_audio_clip_size, streamer.models.validate_audio_clip_type])),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.streamsource')),
            ],
        ),
    ]
