# Generated by Django 5.1.13 on 2025-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mr_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mradmin",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mradmin",
            name="role",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
