@echo off
echo 🔧 Fixing Vite installation issue...

echo Stopping zamio_frontend container...
docker stop zamio_frontend >nul 2>&1
docker rm zamio_frontend >nul 2>&1

echo Removing old frontend image...
docker rmi zamio_backend_zamio_frontend >nul 2>&1

echo Rebuilding frontend container with all dependencies...
cd zamio_backend
docker-compose -f docker-compose.local.yml build --no-cache zamio_frontend

echo Starting frontend container...
docker-compose -f docker-compose.local.yml up -d zamio_frontend

echo ✅ Done! Frontend should be starting up with Vite properly installed...
echo 📱 Access the artist portal at: http://localhost:9002

echo 📋 Showing frontend logs (Ctrl+C to exit)...
docker-compose -f docker-compose.local.yml logs -f zamio_frontend