@echo off
echo 🔄 Restarting frontend with fixes...

echo Stopping zamio_frontend container...
docker stop zamio_frontend >nul 2>&1

echo Starting frontend container...
cd zamio_backend
docker-compose -f docker-compose.local.yml up -d zamio_frontend

echo ✅ Done! Frontend should be starting up...
echo 📱 Access the artist portal at: http://localhost:9002

echo 📋 Showing frontend logs (Ctrl+C to exit)...
docker-compose -f docker-compose.local.yml logs -f zamio_frontend