# Generated by Django 5.1.12 on 2025-09-22 15:29

import django.db.models.deletion
import stations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_id",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=stations.models.get_default_station_image,
                        null=True,
                        upload_to="stations/",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "station_class",
                    models.CharField(
                        choices=[
                            ("class_a", "Class A - Major Metropolitan"),
                            ("class_b", "Class B - Regional"),
                            ("class_c", "Class C - Local/Community"),
                            ("online", "Online Only"),
                            ("community", "Community/Non-Profit"),
                        ],
                        default="class_c",
                        max_length=20,
                    ),
                ),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("public", "Public/Educational"),
                            ("community", "Community"),
                            ("religious", "Religious"),
                            ("online", "Online Only"),
                        ],
                        default="commercial",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Broadcasting license number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "coverage_area",
                    models.CharField(
                        blank=True,
                        help_text="Coverage area description",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "estimated_listeners",
                    models.IntegerField(
                        blank=True, help_text="Estimated daily listeners", null=True
                    ),
                ),
                (
                    "regulatory_body",
                    models.CharField(
                        blank=True,
                        help_text="e.g., GHAMRO, COSGA",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "compliance_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "compliance_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "compliance_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("operating_hours_start", models.TimeField(blank=True, null=True)),
                ("operating_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="Africa/Accra", max_length=50)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("social_media_links", models.JSONField(blank=True, default=dict)),
                (
                    "broadcast_frequency",
                    models.CharField(
                        blank=True, help_text="e.g., 101.5 FM", max_length=20, null=True
                    ),
                ),
                (
                    "transmission_power",
                    models.CharField(
                        blank=True, help_text="e.g., 10kW", max_length=50, null=True
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "momo_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=900, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                (
                    "avg_detection_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("profile", "Complete Profile"),
                            ("staff", "Staff"),
                            ("payment", "Add Payment Info"),
                        ],
                        default="profile",
                        max_length=20,
                    ),
                ),
                ("profile_completed", models.BooleanField(default=False)),
                ("staff_completed", models.BooleanField(default=False)),
                ("report_completed", models.BooleanField(default=False)),
                ("payment_info_added", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_programs",
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Producer", "Producer"),
                            ("Presenter", "Presenter"),
                            ("Dj", "Dj"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_programs",
                        to="stations.stationprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationStreamLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_links",
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Station Manager"),
                            ("producer", "Producer"),
                            ("presenter", "Presenter"),
                            ("dj", "DJ"),
                            ("engineer", "Sound Engineer"),
                            ("admin", "Administrator"),
                            ("compliance_officer", "Compliance Officer"),
                        ],
                        default="presenter",
                        max_length=50,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit"),
                            ("admin", "Administrator"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("can_upload_playlogs", models.BooleanField(default=False)),
                ("can_manage_streams", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_staff",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "unique_together": {("station", "email")},
            },
        ),
    ]
