# Generated by Django 5.1.13 on 2025-10-03 16:47

import stations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='photo',
            field=models.ImageField(blank=True, default=stations.models.get_default_station_image, null=True, upload_to=stations.models.secure_station_image_path, validators=[stations.models.validate_station_image_size, stations.models.validate_station_image_type]),
        ),
    ]
