# Generated by Django 5.1.13 on 2025-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="backup_stream_url",
            field=models.URLField(
                blank=True, help_text="Fallback stream URL for redundancy", null=True
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="bank_branch_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="bank_swift_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="business_registration_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="compliance_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="license_issuing_authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="minimum_payout_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="momo_account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="momo_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="monitoring_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="station",
            name="monitoring_interval_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="station",
            name="payout_frequency",
            field=models.CharField(default="monthly", max_length=20),
        ),
        migrations.AddField(
            model_name="station",
            name="preferred_currency",
            field=models.CharField(default="GHS", max_length=10),
        ),
        migrations.AddField(
            model_name="station",
            name="preferred_payout_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="station_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_auto_restart",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_bitrate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_mount_point",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_quality_check_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_setup_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="stream_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="tax_identification_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("profile", "Complete Profile"),
                    ("stream", "Configure Stream"),
                    ("staff", "Staff"),
                    ("compliance", "Compliance"),
                    ("payment", "Add Payment Info"),
                ],
                default="profile",
                max_length=20,
            ),
        ),
    ]
