# Generated by Django 5.1.13 on 2025-11-01 05:21

from django.db import migrations, models


ROLE_DEFAULTS = {
    'admin': ['reports', 'monitoring', 'staff', 'settings', 'payments', 'compliance'],
    'edit': ['reports', 'monitoring', 'staff'],
    'view': ['reports'],
}


def seed_staff_permissions(apps, schema_editor):
    StationStaff = apps.get_model('stations', 'StationStaff')

    for staff in StationStaff.objects.all():
        name = (staff.name or '').strip()
        first_name = (staff.first_name or '').strip()
        last_name = (staff.last_name or '').strip()

        if name and not first_name and not last_name:
            parts = name.split(' ', 1)
            first_name = parts[0]
            last_name = parts[1] if len(parts) > 1 else ''

        permission_level = (staff.permission_level or 'view').lower()
        defaults = ROLE_DEFAULTS.get(permission_level, ROLE_DEFAULTS['view'])

        can_view_reports = bool(staff.can_view_reports or staff.can_view_analytics or 'reports' in defaults)
        can_monitor_streams = bool(staff.can_monitor_streams or staff.can_manage_streams or 'monitoring' in defaults)
        can_manage_staff = bool(staff.can_manage_staff or 'staff' in defaults)
        can_manage_settings = bool(staff.can_manage_settings or 'settings' in defaults)
        can_manage_payments = bool(staff.can_manage_payments or 'payments' in defaults)
        can_manage_compliance = bool(staff.can_manage_compliance or 'compliance' in defaults)

        StationStaff.objects.filter(pk=staff.pk).update(
            first_name=first_name,
            last_name=last_name,
            can_view_reports=can_view_reports,
            can_monitor_streams=can_monitor_streams,
            can_manage_staff=can_manage_staff,
            can_manage_settings=can_manage_settings,
            can_manage_payments=can_manage_payments,
            can_manage_compliance=can_manage_compliance,
        )


def rollback_staff_permissions(apps, schema_editor):
    StationStaff = apps.get_model('stations', 'StationStaff')
    StationStaff.objects.update(
        first_name='',
        last_name='',
        can_view_reports=False,
        can_monitor_streams=False,
        can_manage_staff=False,
        can_manage_settings=False,
        can_manage_payments=False,
        can_manage_compliance=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_station_cover_image_station_founded_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationstaff",
            name="can_manage_compliance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="can_manage_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="can_manage_settings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="can_manage_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="can_monitor_streams",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="stationstaff",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(seed_staff_permissions, rollback_staff_permissions),
    ]
