import React from 'react';
import {
  // Navigation & UI
  HomeIcon,
  Cog6ToothIcon as SettingsIcon,
  UserIcon,
  UsersIcon,
  BuildingOfficeIcon,
  RadioIcon,
  MusicalNoteIcon,
  ChartBarIcon,
  DocumentTextIcon,
  BellIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  PencilIcon,
  TrashIcon,
  EyeIcon,
  EyeSlashIcon,
  ArrowUpTrayIcon as UploadIcon,
  ArrowDownTrayIcon as DownloadIcon,
  
  // Status & Actions
  CheckIcon,
  XMarkIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  
  // Navigation
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  
  // Media & Content
  PhotoIcon,
  VideoCameraIcon,
  MicrophoneIcon,
  SpeakerWaveIcon,
  HeadphonesIcon,
  
  // Communication
  EnvelopeIcon,
  PhoneIcon,
  ChatBubbleLeftRightIcon,
  
  // Finance & Business
  BanknotesIcon,
  CreditCardIcon,
  ChartPieIcon,
  PresentationChartLineIcon,
  
  // System
  ServerIcon,
  CloudIcon,
  ShieldCheckIcon,
  LockClosedIcon,
  KeyIcon,
  
  // Social & Sharing
  ShareIcon,
  HeartIcon,
  StarIcon,
  
  // Menu & Layout
  Bars3Icon as MenuIcon,
  XMarkIcon as CloseIcon,
  EllipsisVerticalIcon as MoreVerticalIcon,
  EllipsisHorizontalIcon as MoreHorizontalIcon,
  
  // Theme
  SunIcon,
  MoonIcon,
} from '@heroicons/react/24/outline';

import {
  // Filled versions for active states
  HomeIcon as HomeIconSolid,
  UserIcon as UserIconSolid,
  MusicalNoteIcon as MusicalNoteIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  BellIcon as BellIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  HeartIcon as HeartIconSolid,
  StarIcon as StarIconSolid,
} from '@heroicons/react/24/solid';

// Lucide React icons for additional variety
import {
  Music,
  Headphones,
  Radio as RadioLucide,
  Mic,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Download,
  Upload,
  Share2,
  Heart,
  Star,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Shield,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Wifi,
  WifiOff,
  Signal,
  Battery,
  Bluetooth,
  Smartphone,
  Tablet,
  Monitor,
  Tv,
  Camera,
  Image,
  File,
  FileText,
  Folder,
  FolderOpen,
  Archive,
  Trash2,
  Edit3,
  Copy,
  Clipboard,
  Link,
  ExternalLink,
  Mail,
  Phone,
  MessageCircle,
  Send,
  Inbox,
  Archive as ArchiveLucide,
  Bookmark,
  Flag,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign,
  CreditCard,
  Wallet,
  ShoppingCart,
  Package,
  Truck,
  MapPin as LocationIcon,
  Navigation,
  Compass,
  Map,
  Users as UsersLucide,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Crown,
  Award,
  Medal,
  Trophy,
  Target,
  Crosshair,
  Focus,
  Layers,
  Grid,
  List,
  LayoutGrid,
  LayoutList,
  Sidebar,
  PanelLeft,
  PanelRight,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Power,
  Settings as SettingsLucide,
  Sliders,
  ToggleLeft,
  ToggleRight,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Diamond,
  Plus,
  Minus,
  X,
  Check,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  CornerUpRight,
  CornerDownRight,
  CornerDownLeft,
  CornerUpLeft,
  Move,
  MousePointer,
  Hand,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Printer,
  Scanner,
  Fax,
  HardDrive,
  Cpu,
  MemoryStick,
  Database,
  Server,
  Cloud as CloudLucide,
  CloudDownload,
  CloudUpload,
  CloudOff,
  Wifi as WifiLucide,
  Bluetooth as BluetoothLucide,
  Usb,
  Ethernet,
  Router,
  Antenna,
  Satellite,
  Radar,
  Radio as RadioIcon,
  Tv as TvLucide,
  Monitor as MonitorLucide,
  Smartphone as SmartphoneLucide,
  Tablet as TabletLucide,
  Laptop,
  Watch,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Spade,
  Club,
  Heart as HeartLucide,
  Diamond as DiamondLucide,
} from 'lucide-react';

export interface IconProps {
  className?: string;
  size?: number | string;
  color?: string;
}

// Common icon sizes
export const iconSizes = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
  '2xl': 48,
} as const;

// Icon categories for easy organization
export const NavigationIcons = {
  Home: HomeIcon,
  HomeSolid: HomeIconSolid,
  Settings: SettingsIcon,
  User: UserIcon,
  UserSolid: UserIconSolid,
  Users: UsersIcon,
  Building: BuildingOfficeIcon,
  Radio: RadioIcon,
  Music: MusicalNoteIcon,
  MusicSolid: MusicalNoteIconSolid,
  Chart: ChartBarIcon,
  ChartSolid: ChartBarIconSolid,
  Document: DocumentTextIcon,
  Bell: BellIcon,
  BellSolid: BellIconSolid,
  Search: MagnifyingGlassIcon,
  Menu: MenuIcon,
  Close: CloseIcon,
  MoreVertical: MoreVerticalIcon,
  MoreHorizontal: MoreHorizontalIcon,
};

export const ActionIcons = {
  Plus: PlusIcon,
  Edit: PencilIcon,
  Delete: TrashIcon,
  View: EyeIcon,
  Hide: EyeSlashIcon,
  Upload: UploadIcon,
  Download: DownloadIcon,
  Share: ShareIcon,
  Copy: Copy,
  Link: Link,
  ExternalLink: ExternalLink,
};

export const StatusIcons = {
  Check: CheckIcon,
  CheckCircle: CheckCircleIcon,
  CheckCircleSolid: CheckCircleIconSolid,
  X: XMarkIcon,
  XCircle: XCircleIcon,
  XCircleSolid: XCircleIconSolid,
  Warning: ExclamationTriangleIcon,
  WarningSolid: ExclamationTriangleIconSolid,
  Info: InformationCircleIcon,
  InfoSolid: InformationCircleIconSolid,
  Clock: ClockIcon,
  Loading: RefreshCw,
};

export const MediaIcons = {
  Play: PlayIcon,
  Pause: PauseIcon,
  Stop: StopIcon,
  SkipBack: SkipBack,
  SkipForward: SkipForward,
  Shuffle: Shuffle,
  Repeat: Repeat,
  Volume: SpeakerWaveIcon,
  Headphones: HeadphonesIcon,
  Microphone: MicrophoneIcon,
  Camera: VideoCameraIcon,
  Photo: PhotoIcon,
  Music: Music,
  Radio: RadioLucide,
};

export const ThemeIcons = {
  Sun: SunIcon,
  Moon: MoonIcon,
  Light: SunIcon,
  Dark: MoonIcon,
};

export const ArrowIcons = {
  Left: ChevronLeftIcon,
  Right: ChevronRightIcon,
  Up: ChevronUpIcon,
  Down: ChevronDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
};

export const BusinessIcons = {
  Money: BanknotesIcon,
  CreditCard: CreditCardIcon,
  Wallet: Wallet,
  Chart: ChartPieIcon,
  Presentation: PresentationChartLineIcon,
  TrendingUp: TrendingUp,
  BarChart: BarChart3,
  PieChart: PieChart,
  Activity: Activity,
  Target: Target,
  Award: Award,
  Trophy: Trophy,
};

export const CommunicationIcons = {
  Email: EnvelopeIcon,
  Phone: PhoneIcon,
  Chat: ChatBubbleLeftRightIcon,
  Message: MessageCircle,
  Send: Send,
  Inbox: Inbox,
  Mail: Mail,
};

export const SystemIcons = {
  Server: ServerIcon,
  Cloud: CloudIcon,
  Shield: ShieldCheckIcon,
  Lock: LockClosedIcon,
  Key: KeyIcon,
  Database: Database,
  Cpu: Cpu,
  HardDrive: HardDrive,
  Wifi: Wifi,
  Signal: Signal,
  Battery: Battery,
  Power: Power,
};

// Export all icons for direct use
export {
  // Heroicons
  HomeIcon,
  HomeIconSolid,
  SettingsIcon,
  UserIcon,
  UserIconSolid,
  UsersIcon,
  BuildingOfficeIcon,
  RadioIcon,
  MusicalNoteIcon,
  MusicalNoteIconSolid,
  ChartBarIcon,
  ChartBarIconSolid,
  DocumentTextIcon,
  BellIcon,
  BellIconSolid,
  MagnifyingGlassIcon,
  PlusIcon,
  PencilIcon,
  TrashIcon,
  EyeIcon,
  EyeSlashIcon,
  UploadIcon,
  DownloadIcon,
  CheckIcon,
  XMarkIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  PhotoIcon,
  VideoCameraIcon,
  MicrophoneIcon,
  SpeakerWaveIcon,
  HeadphonesIcon,
  EnvelopeIcon,
  PhoneIcon,
  ChatBubbleLeftRightIcon,
  BanknotesIcon,
  CreditCardIcon,
  ChartPieIcon,
  PresentationChartLineIcon,
  ServerIcon,
  CloudIcon,
  ShieldCheckIcon,
  LockClosedIcon,
  KeyIcon,
  ShareIcon,
  HeartIcon,
  StarIcon,
  MenuIcon,
  CloseIcon,
  MoreVerticalIcon,
  MoreHorizontalIcon,
  SunIcon,
  MoonIcon,
  
  // Lucide React
  Music,
  Headphones,
  RadioLucide,
  Mic,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Download,
  Upload,
  Share2,
  Heart,
  Star,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Shield,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Wifi,
  WifiOff,
  Signal,
  Battery,
  Bluetooth,
  Smartphone,
  Tablet,
  Monitor,
  Tv,
  Camera,
  Image,
  File,
  FileText,
  Folder,
  FolderOpen,
  Archive,
  Trash2,
  Edit3,
  Copy,
  Clipboard,
  Link,
  ExternalLink,
  Mail,
  Phone,
  MessageCircle,
  Send,
  Inbox,
  ArchiveLucide,
  Bookmark,
  Flag,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign,
  CreditCard,
  Wallet,
  ShoppingCart,
  Package,
  Truck,
  LocationIcon,
  Navigation,
  Compass,
  Map,
  UsersLucide,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Crown,
  Award,
  Medal,
  Trophy,
  Target,
  Crosshair,
  Focus,
  Layers,
  Grid,
  List,
  LayoutGrid,
  LayoutList,
  Sidebar,
  PanelLeft,
  PanelRight,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Power,
  SettingsLucide,
  Sliders,
  ToggleLeft,
  ToggleRight,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Diamond,
  Plus,
  Minus,
  X,
  Check,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  CornerUpRight,
  CornerDownRight,
  CornerDownLeft,
  CornerUpLeft,
  Move,
  MousePointer,
  Hand,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Printer,
  Scanner,
  Fax,
  HardDrive,
  Cpu,
  MemoryStick,
  Database,
  Server,
  CloudLucide,
  CloudDownload,
  CloudUpload,
  CloudOff,
  WifiLucide,
  BluetoothLucide,
  Usb,
  Ethernet,
  Router,
  Antenna,
  Satellite,
  Radar,
  RadioIcon,
  TvLucide,
  MonitorLucide,
  SmartphoneLucide,
  TabletLucide,
  Laptop,
  Watch,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Spade,
  Club,
  HeartLucide,
  DiamondLucide,
};