# Generated by Django 5.1.13 on 2025-11-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("stations", "0003_stationstaff_can_manage_compliance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_notifications",
                to="stations.station",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Summary", "Summary"),
                    ("Compliance", "Compliance"),
                    ("Update", "Update"),
                    ("Pending", "Pending"),
                    ("system", "System Alert"),
                    ("performance", "Performance"),
                    ("content", "Content"),
                    ("compliance", "Compliance Alert"),
                    ("financial", "Financial"),
                    ("social", "Social"),
                    ("technical", "Technical"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
