# Generated by Django 5.1.13 on 2025-10-30 14:11

import django.db.models.deletion
import publishers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("sent_on", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_invite",
                        to="artists.track",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublisherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher_id",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_type", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("primary_contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "compliance_officer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "compliance_officer_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "compliance_officer_phone",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "compliance_officer_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=900, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("bank_account", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=150)),
                ("bank_branch_code", models.CharField(blank=True, max_length=50)),
                ("bank_swift_code", models.CharField(blank=True, max_length=50)),
                ("momo_account", models.CharField(blank=True, max_length=100)),
                ("momo_account_name", models.CharField(blank=True, max_length=150)),
                ("momo_provider", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_payment_method",
                    models.CharField(blank=True, max_length=20),
                ),
                ("payout_currency", models.CharField(blank=True, max_length=10)),
                ("payout_frequency", models.CharField(blank=True, max_length=20)),
                (
                    "minimum_payout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "vat_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "writer_split",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "publisher_split",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "mechanical_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "performance_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sync_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "administrative_fee_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("revenue_split_notes", models.TextField(blank=True)),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("profile", "Complete Profile"),
                            ("revenue-split", "Revenue Split"),
                            ("link-artist", "Sign Link Artist"),
                            ("payment", "Add Payment Info"),
                        ],
                        default="profile",
                        max_length=20,
                    ),
                ),
                ("profile_completed", models.BooleanField(default=False)),
                ("revenue_split_completed", models.BooleanField(default=False)),
                ("link_artist_completed", models.BooleanField(default=False)),
                ("payment_info_added", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublisherArtistRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("exclusive", "Exclusive Publishing"),
                            ("co_publishing", "Co-Publishing"),
                            ("administration", "Administration Only"),
                            ("sub_publishing", "Sub-Publishing"),
                        ],
                        default="exclusive",
                        max_length=20,
                    ),
                ),
                ("territory", models.CharField(default="Ghana", max_length=100)),
                ("worldwide", models.BooleanField(default=False)),
                (
                    "royalty_split_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Publisher's percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "advance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload contract document (PDF, DOC, DOCX, or image files only)",
                        upload_to=publishers.models.secure_contract_upload_path,
                        validators=[publishers.models.validate_contract_file],
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for file integrity",
                        max_length=64,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Contract version number"
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times file has been accessed"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, help_text="Last time file was accessed", null=True
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False, help_text="File quarantined for security reasons"
                    ),
                ),
                (
                    "quarantine_reason",
                    models.TextField(blank=True, help_text="Reason for quarantine"),
                ),
                ("quarantined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Approval"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_by_admin", models.BooleanField(default=False)),
                ("approved_by_artist", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_relationships",
                        to="artists.artist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to previous version of this contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newer_versions",
                        to="publishers.publisherartistrelationship",
                    ),
                ),
                (
                    "quarantined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantined_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_relationships",
                        to="publishers.publisherprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publisher", "status"],
                        name="publishers__publish_57e4de_idx",
                    ),
                    models.Index(
                        fields=["artist", "status"],
                        name="publishers__artist__c42b7f_idx",
                    ),
                    models.Index(
                        fields=["status", "start_date"],
                        name="publishers__status_a7ae57_idx",
                    ),
                ],
                "unique_together": {("publisher", "artist", "territory")},
            },
        ),
        migrations.CreateModel(
            name="PublishingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer_share", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "publisher_share",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload contract document (PDF, DOC, DOCX, or image files only)",
                        upload_to=publishers.models.secure_contract_upload_path,
                        validators=[publishers.models.validate_contract_file],
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for file integrity",
                        max_length=64,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Contract version number"
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times file has been accessed"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, help_text="Last time file was accessed", null=True
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False, help_text="File quarantined for security reasons"
                    ),
                ),
                (
                    "quarantine_reason",
                    models.TextField(blank=True, help_text="Reason for quarantine"),
                ),
                ("quarantined_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by_admin", models.BooleanField(default=False)),
                ("agreement_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to previous version of this contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newer_versions",
                        to="publishers.publishingagreement",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishers.publisherprofile",
                    ),
                ),
                (
                    "quarantined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantined_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "songwriter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_songs",
                        to="artists.artist",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artists.track"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publisher", "status"],
                        name="publishers__publish_8bd7ea_idx",
                    ),
                    models.Index(
                        fields=["songwriter", "status"],
                        name="publishers__songwri_12a792_idx",
                    ),
                    models.Index(
                        fields=["track", "status"],
                        name="publishers__track_i_1a73ca_idx",
                    ),
                    models.Index(
                        fields=["version", "created_at"],
                        name="publishers__version_83b907_idx",
                    ),
                ],
            },
        ),
    ]
