# Generated by Django 5.1.13 on 2025-11-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherAccountSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("royalty_alerts", models.BooleanField(default=True)),
                ("weekly_reports", models.BooleanField(default=False)),
                ("two_factor_auth", models.BooleanField(default=False)),
                ("preferred_language", models.CharField(default="en", max_length=16)),
                ("timezone", models.CharField(default="UTC", max_length=128)),
                ("currency", models.CharField(default="GHS", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publisher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_settings",
                        to="publishers.publisherprofile",
                    ),
                ),
            ],
        ),
    ]
