# Generated by Django 4.2.7 on 2025-10-02 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publishers.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="access_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times file has been accessed"
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="file_hash",
            field=models.CharField(
                blank=True, help_text="SHA-256 hash for file integrity", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="File size in bytes"
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="is_quarantined",
            field=models.BooleanField(
                default=False, help_text="File quarantined for security reasons"
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True, help_text="Last time file was accessed", null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="original_filename",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to previous version of this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_versions",
                to="publishers.publisherartistrelationship",
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="quarantine_reason",
            field=models.TextField(blank=True, help_text="Reason for quarantine"),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="quarantined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="quarantined_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quarantined_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publisherartistrelationship",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Contract version number"
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="access_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times file has been accessed"
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="file_hash",
            field=models.CharField(
                blank=True, help_text="SHA-256 hash for file integrity", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="File size in bytes"
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="is_quarantined",
            field=models.BooleanField(
                default=False, help_text="File quarantined for security reasons"
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True, help_text="Last time file was accessed", null=True
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="original_filename",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to previous version of this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_versions",
                to="publishers.publishingagreement",
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="quarantine_reason",
            field=models.TextField(blank=True, help_text="Reason for quarantine"),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="quarantined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="quarantined_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quarantined_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publishingagreement",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Contract version number"
            ),
        ),
        migrations.AlterField(
            model_name="publisherartistrelationship",
            name="contract_file",
            field=models.FileField(
                blank=True,
                help_text="Upload contract document (PDF, DOC, DOCX, or image files only)",
                upload_to=publishers.models.secure_contract_upload_path,
                validators=[publishers.models.validate_contract_file],
            ),
        ),
        migrations.AlterField(
            model_name="publishingagreement",
            name="contract_file",
            field=models.FileField(
                blank=True,
                help_text="Upload contract document (PDF, DOC, DOCX, or image files only)",
                upload_to=publishers.models.secure_contract_upload_path,
                validators=[publishers.models.validate_contract_file],
            ),
        ),
        migrations.AddIndex(
            model_name="publishingagreement",
            index=models.Index(
                fields=["publisher", "status"], name="publishers__publish_8bd7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishingagreement",
            index=models.Index(
                fields=["songwriter", "status"], name="publishers__songwri_12a792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishingagreement",
            index=models.Index(
                fields=["track", "status"], name="publishers__track_i_1a73ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishingagreement",
            index=models.Index(
                fields=["version", "created_at"], name="publishers__version_83b907_idx"
            ),
        ),
    ]
