# Generated by Django 5.1.13 on 2025-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisherprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="administrative_fee_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="bank_branch_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="bank_swift_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="business_registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="company_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="compliance_officer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="compliance_officer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="compliance_officer_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="compliance_officer_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="employee_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="founded_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="mechanical_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="minimum_payout_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="momo_account_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="momo_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="payout_currency",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="payout_frequency",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="performance_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="preferred_payment_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="primary_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="primary_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="primary_contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="revenue_split_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="sync_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="vat_registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="publisherprofile",
            name="withholding_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
