# Generated by Django 5.1.13 on 2025-10-22 06:36

import uuid
from django.db import migrations, models


def populate_user_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    users_without_id = User.objects.filter(user_id__isnull=True)
    for user in users_without_id.iterator():
        user.user_id = uuid.uuid4()
        user.save(update_fields=["user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_user_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
