# Generated by Django 4.2.7 on 2025-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
