# Generated by Django 5.1.13 on 2025-10-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id_card", "National ID Card"),
                    ("passport", "Passport"),
                    ("drivers_license", "Driver's License"),
                    ("utility_bill", "Utility Bill"),
                    ("bank_statement", "Bank Statement"),
                    ("business_registration", "Business Registration"),
                    ("tax_certificate", "Tax Certificate"),
                    ("selfie", "Selfie Verification"),
                ],
                max_length=50,
            ),
        ),
    ]
