# Generated by Django 5.1.13 on 2025-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_kycdocument_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="file_hash",
            field=models.CharField(max_length=64),
        ),
    ]
