# Generated by Django 4.2.7 on 2025-10-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_verification_code_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
