# Generated by Django 4.2.7 on 2025-10-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_location_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_skipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("skipped", "Skipped"),
                    ("incomplete", "Incomplete"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
