# Generated by Django 5.1.13 on 2025-11-05 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_type', models.CharField(choices=[('dashboard', 'Dashboard Data'), ('report', 'Report Data'), ('export', 'Export Data'), ('realtime', 'Real-time Data')], max_length=20)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('data_size_bytes', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_type', 'expires_at'], name='analytics_a_cache_t_94d7b2_idx'), models.Index(fields=['user_id', 'cache_type'], name='analytics_a_user_id_051443_idx'), models.Index(fields=['expires_at'], name='analytics_a_expires_4e35a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('snapshot_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('metric_type', models.CharField(choices=[('plays', 'Play Count'), ('revenue', 'Revenue'), ('detections', 'Detection Count'), ('confidence', 'Average Confidence'), ('unique_tracks', 'Unique Tracks'), ('unique_stations', 'Unique Stations'), ('system_health', 'System Health')], max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('artist_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('station_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('publisher_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_type', 'metric_type', 'period_start'], name='analytics_a_snapsho_c89c42_idx'), models.Index(fields=['artist_id', 'metric_type', 'period_start'], name='analytics_a_artist__0b487a_idx'), models.Index(fields=['station_id', 'metric_type', 'period_start'], name='analytics_a_station_a6bbbf_idx'), models.Index(fields=['publisher_id', 'metric_type', 'period_start'], name='analytics_a_publish_1b13d2_idx'), models.Index(fields=['region', 'metric_type', 'period_start'], name='analytics_a_region_7b76cb_idx')],
                'unique_together': {('snapshot_type', 'metric_type', 'period_start', 'artist_id', 'station_id', 'publisher_id', 'track_id', 'region')},
            },
        ),
        migrations.CreateModel(
            name='RealtimeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('active_detections', 'Active Detections'), ('processing_queue', 'Processing Queue Size'), ('system_load', 'System Load'), ('error_rate', 'Error Rate'), ('revenue_today', 'Revenue Today'), ('plays_today', 'Plays Today')], db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('station_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('artist_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='analytics_r_metric__2b25f9_idx'), models.Index(fields=['station_id', 'metric_name', 'timestamp'], name='analytics_r_station_679cd7_idx'), models.Index(fields=['artist_id', 'metric_name', 'timestamp'], name='analytics_r_artist__e8f896_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_date_range', models.CharField(choices=[('7d', 'Last 7 Days'), ('30d', 'Last 30 Days'), ('90d', 'Last 90 Days'), ('1y', 'Last Year'), ('custom', 'Custom Range')], default='30d', max_length=20)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('favorite_metrics', models.JSONField(blank=True, default=list)),
                ('email_reports', models.BooleanField(default=True)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('preferred_export_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('export_type', models.CharField(choices=[('artist_analytics', 'Artist Analytics'), ('publisher_analytics', 'Publisher Analytics'), ('station_analytics', 'Station Analytics'), ('admin_analytics', 'Admin Analytics'), ('royalty_report', 'Royalty Report'), ('detection_report', 'Detection Report')], max_length=30)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='analytics_a_user_id_a37e7b_idx'), models.Index(fields=['export_type', 'requested_at'], name='analytics_a_export__0c7864_idx'), models.Index(fields=['status', 'requested_at'], name='analytics_a_status_acff63_idx'), models.Index(fields=['expires_at'], name='analytics_a_expires_d88bec_idx')],
            },
        ),
    ]
