# Generated by Django 4.2.7 on 2025-10-08 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artists", "0003_album_cover_art_hash_album_last_malware_scan_and_more"),
        ("publishers", "0002_add_contract_security_fields"),
        ("royalties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoyaltyWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "withdrawal_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "requester_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("publisher", "Publisher"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("publishing_status_validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_details", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artists.artist",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishers.publisherprofile",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="royalty_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["requester", "status"],
                        name="royalties_r_request_65d2c2_idx",
                    ),
                    models.Index(
                        fields=["artist", "status"],
                        name="royalties_r_artist__e205ec_idx",
                    ),
                    models.Index(
                        fields=["publisher", "status"],
                        name="royalties_r_publish_7d8fd3_idx",
                    ),
                    models.Index(
                        fields=["status", "requested_at"],
                        name="royalties_r_status_8aadd9_idx",
                    ),
                ],
            },
        ),
    ]
