# Generated by Django 4.2.7 on 2025-10-21 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="track_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="platformavailability",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.track"
            ),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fingerprint_track",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributor_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_artists",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.genre",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadprocessingstatus",
            index=models.Index(
                fields=["upload_id"], name="artists_upl_upload__4076ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadprocessingstatus",
            index=models.Index(
                fields=["user", "status"], name="artists_upl_user_id_f82ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadprocessingstatus",
            index=models.Index(
                fields=["status", "created_at"], name="artists_upl_status_b90f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(fields=["hash"], name="artists_fin_hash_58b110_idx"),
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(
                fields=["track", "processing_status"],
                name="artists_fin_track_i_344b6c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fingerprint",
            unique_together={("track", "hash", "offset")},
        ),
    ]
