# Generated by Django 5.1.12 on 2025-09-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("fan", "0001_initial"),
        ("publishers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="album_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="fan.fan"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artist_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
            ),
        ),
        migrations.AddField(
            model_name="artistgenre",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_genre",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="artistinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_invitations",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributor_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artistgenre",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.genre"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.album",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.genre",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="track_publishers",
                to="publishers.publisherprofile",
            ),
        ),
        migrations.AddField(
            model_name="platformavailability",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.track"
            ),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fingerprint_track",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="trackfeedback",
            name="fan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fan_feedback",
                to="fan.fan",
            ),
        ),
        migrations.AddField(
            model_name="trackfeedback",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_feedback",
                to="artists.track",
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(
                fields=["hash", "track_id"], name="artists_fin_hash_c3790a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(
                fields=["version", "algorithm"], name="artists_fin_version_5c1dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(
                fields=["processing_status"], name="artists_fin_process_48dbc8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fingerprint",
            unique_together={("track", "offset", "hash", "version")},
        ),
    ]
