# Generated by Django 5.1.13 on 2025-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='onboarding_step',
            field=models.CharField(default='profile', max_length=32),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_info_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='publisher_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_media_added',
            field=models.BooleanField(default=False),
        ),
    ]
