# Generated by Django 5.1.13 on 2025-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_track_catalog_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadprocessingstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
