# Generated by Django 5.1.13 on 2025-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_onboarding_step_artist_payment_info_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='onboarding_step',
            field=models.CharField(choices=[('profile', 'Profile'), ('social-media', 'Social Media'), ('payment', 'Payment'), ('publisher', 'Publisher'), ('done', 'Done')], default='profile', max_length=32),
        ),
    ]
