# Generated by Django 5.1.13 on 2025-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0004_alter_artist_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("social-media", "Social Media"),
                    ("payment", "Payment"),
                    ("publisher", "Publisher"),
                    ("kyc", "Identity Verification"),
                    ("done", "Done"),
                ],
                default="profile",
                max_length=32,
            ),
        ),
    ]
