# Generated by Django 5.1.13 on 2025-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0004_alter_artist_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="music_style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="payment_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="artist",
            name="publisher_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="artist",
            name="primary_genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="social_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
