# Generated by Django 5.1.13 on 2025-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0005_artist_country_artist_music_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("social-media", "Social Media"),
                    ("payment", "Payment"),
                    ("publisher", "Publisher"),
                    ("kyc", "Identity Verification"),
                    ("done", "Done"),
                ],
                default="profile",
                max_length=32,
            ),
        ),
    ]
