# Generated by Django 5.1.13 on 2025-10-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0006_alter_artist_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistIdentityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_legal_name",
                    models.CharField(max_length=255),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("ghana_card", "Ghana Card"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("voter_id", "Voter ID"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(max_length=120),
                ),
                (
                    "residential_address",
                    models.TextField(),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="identity_profile",
                        to="artists.artist",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="artistidentityprofile",
            index=models.Index(fields=["artist"], name="artists_art_artist_9f629e_idx"),
        ),
        migrations.AddIndex(
            model_name="artistidentityprofile",
            index=models.Index(fields=["id_type"], name="artists_art_id_type_7d1a5a_idx"),
        ),
    ]

