# Generated by Django 5.1.13 on 2025-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0007_artistidentityprofile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="artistidentityprofile",
            new_name="artists_art_artist__bf845a_idx",
            old_name="artists_art_artist_9f629e_idx",
        ),
        migrations.RenameIndex(
            model_name="artistidentityprofile",
            new_name="artists_art_id_type_08d5eb_idx",
            old_name="artists_art_id_type_7d1a5a_idx",
        ),
        migrations.AddField(
            model_name="uploadprocessingstatus",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
