# Generated by Django 5.1.12 on 2025-09-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0002_initial"),
        ("disputes", "0001_initial"),
        ("music_monitor", "0001_initial"),
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="related_detection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_monitor.audiodetection",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_royalty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_monitor.royaltydistribution",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disputeauditlog",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="disputeauditlog",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="disputes.dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputecomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="disputecomment",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="disputes.dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputecomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="disputes.disputecomment",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="disputes.dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="disputenotification",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="disputes.dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputenotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="disputeworkflowrule",
            unique_together={("from_status", "to_status")},
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "priority"], name="disputes_di_status_3dbe35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["dispute_type", "created_at"],
                name="disputes_di_dispute_6ae0e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["submitted_by", "status"], name="disputes_di_submitt_df466c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeauditlog",
            index=models.Index(
                fields=["dispute", "timestamp"], name="disputes_di_dispute_b40e65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeauditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="disputes_di_actor_i_592d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputenotification",
            index=models.Index(
                fields=["recipient", "read_at"], name="disputes_di_recipie_a0588c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputenotification",
            index=models.Index(
                fields=["dispute", "sent_at"], name="disputes_di_dispute_4c9bd4_idx"
            ),
        ),
    ]
