# Generated by Django 4.2 on 2025-10-19 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disputes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations", "0001_initial"),
        ("artists", "0002_initial"),
        ("music_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="related_detection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_monitor.audiodetection",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_royalty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_monitor.royaltydistribution",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="related_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="disputenotification",
            index=models.Index(
                fields=["recipient", "read_at"], name="disputes_di_recipie_a0588c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputenotification",
            index=models.Index(
                fields=["dispute", "sent_at"], name="disputes_di_dispute_4c9bd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["dispute", "uploaded_at"], name="disputes_di_dispute_27a410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="disputes_di_uploade_4d5d6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["file_hash"], name="disputes_di_file_ha_50cc32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["is_quarantined"], name="disputes_di_is_quar_d418ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["delete_after"], name="disputes_di_delete__411dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeauditlog",
            index=models.Index(
                fields=["dispute", "timestamp"], name="disputes_di_dispute_b40e65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeauditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="disputes_di_actor_i_592d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "priority"], name="disputes_di_status_3dbe35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["dispute_type", "created_at"],
                name="disputes_di_dispute_6ae0e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["submitted_by", "status"], name="disputes_di_submitt_df466c_idx"
            ),
        ),
    ]
