# Generated by Django 4.2.7 on 2025-10-02 17:40

import disputes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disputes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputeevidence",
            name="access_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="delete_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="file_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="is_quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="quarantine_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="retention_policy",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="disputeevidence",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=disputes.models.secure_evidence_upload_path,
                validators=[disputes.models.validate_evidence_file],
            ),
        ),
        migrations.AlterField(
            model_name="disputeevidence",
            name="file_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["dispute", "uploaded_at"], name="disputes_di_dispute_27a410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="disputes_di_uploade_4d5d6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["file_hash"], name="disputes_di_file_ha_50cc32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["is_quarantined"], name="disputes_di_is_quar_d418ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["delete_after"], name="disputes_di_delete__411dea_idx"
            ),
        ),
    ]
