# Generated by Django 5.1.12 on 2025-09-22 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=20, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="Ghc", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Requested", "Requested"),
                            ("Paid", "Paid"),
                            ("Declined", "Declined"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN MoMo", "MTN MoMo"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="Ghc", max_length=50, null=True
                    ),
                ),
                ("requested_on", models.DateTimeField(blank=True, null=True)),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                ("declined_on", models.DateTimeField(blank=True, null=True)),
                ("date_processed", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Deposit", "Deposit"),
                            ("Withdrawal", "Withdrawal"),
                            ("Transfer", "Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bank_account.bankaccount",
                    ),
                ),
            ],
        ),
    ]
