# Generated by Django 4.2 on 2025-10-19 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations", "0001_initial"),
        ("royalties", "0001_initial"),
        ("artists", "0002_initial"),
        ("music_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="royaltydistribution",
            name="external_pro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="royalties.partnerpro",
            ),
        ),
        migrations.AddField(
            model_name="royaltydistribution",
            name="play_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="royalty_distributions",
                to="music_monitor.playlog",
            ),
        ),
        migrations.AddField(
            model_name="royaltydistribution",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_royalties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="royaltydistribution",
            name="reciprocal_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="royalties.reciprocalagreement",
            ),
        ),
        migrations.AddField(
            model_name="playlog",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_playlog",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="playlog",
            name="station_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_program_playlog",
                to="stations.stationprogram",
            ),
        ),
        migrations.AddField(
            model_name="playlog",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_playlog",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="matchcache",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_station",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="matchcache",
            name="station_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_station_program",
                to="stations.stationprogram",
            ),
        ),
        migrations.AddField(
            model_name="matchcache",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_track",
                to="artists.track",
            ),
        ),
        migrations.AddField(
            model_name="failedplaylog",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="music_monitor.matchcache",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="playlog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute_playlog",
                to="music_monitor.playlog",
            ),
        ),
        migrations.AddField(
            model_name="audiodetection",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_detections",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="audiodetection",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="artists.track",
            ),
        ),
        migrations.AddIndex(
            model_name="royaltydistribution",
            index=models.Index(
                fields=["recipient", "status"], name="music_monit_recipie_3ab046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaltydistribution",
            index=models.Index(
                fields=["play_log", "recipient_type"],
                name="music_monit_play_lo_abcf2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="royaltydistribution",
            index=models.Index(
                fields=["status", "calculated_at"], name="music_monit_status_d7598b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaltydistribution",
            index=models.Index(
                fields=["external_pro", "status"], name="music_monit_externa_0a3c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaltydistribution",
            index=models.Index(
                fields=["currency", "calculated_at"],
                name="music_monit_currenc_e03086_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(
                fields=["station", "detected_at"], name="music_monit_station_685980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(
                fields=["detection_source", "confidence_score"],
                name="music_monit_detecti_575b4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(fields=["isrc"], name="music_monit_isrc_5ed11c_idx"),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(
                fields=["pro_affiliation", "detected_at"],
                name="music_monit_pro_aff_732fdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(
                fields=["processing_status"], name="music_monit_process_a29844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiodetection",
            index=models.Index(
                fields=["session_id", "audio_timestamp"],
                name="music_monit_session_2d3819_idx",
            ),
        ),
    ]
