# Generated by Django 5.1.13 on 2025-11-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_monitor", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippetingest",
            name="audio_detection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snippet",
                to="music_monitor.audiodetection",
            ),
        ),
        migrations.AddField(
            model_name="snippetingest",
            name="file_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snippetingest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
