# Generated by Django 5.1.13 on 2025-11-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_uploadprocessingstatus_status'),
        ('music_monitor', '0003_snippetingest_audio_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcache',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_track', to='artists.track'),
        ),
    ]
